version: '3'

services:
  peatio:
    build:
      context: peatio
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
      - rabbitmq
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASS=changeme
      - RABBITMQ_HOST=rabbitmq
      - SMTP_PORT=25
      - SMTP_DOMAIN=helioscloud.com
      - SMTP_ADDRESS=smtp-relay
      - SMTP_USE_SSL=false
      - SMTP_USE_TLS=false
      - SMTP_ENABLE_STARTTLS=false
      - SMTP_ENABLE_STARTTLS_AUTO=false
    volumes:
      - ./peatio:/home/app
    entrypoint:
      - /bin/sh
      - -xc
    command:
      - |
        ./bin/init_config
        bundle exec puma --config config/puma.rb

  peatio_daemons:
    build:
      context: peatio
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
      - redis
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASS=changeme
      - RABBITMQ_HOST=rabbitmq
    command: god -c lib/daemons/daemons.god -D start

  peatio_specs:
    build:
      context: peatio
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
      - rabbitmq
    environment:
      - PORT=8000
      - RAILS_ENV=test
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASS=changeme
      - RABBITMQ_HOST=rabbitmq
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
      - TEST_APP_HOST=peatio
      - TEST_APP_PORT=8080
    volumes:
      - ./peatio:/home/app
    entrypoint:
      - /bin/sh
      - -exc
    command:
      - |
        bundle exec rspec --exclude-pattern=spec/features/**/*_spec.rb

  smtp-relay:
    image: kaigara/postfix:latest
    volumes:
      - ./smtp-relay.yaml:/etc/kaigara/metadata/relay.yml

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: peatio_development
      MYSQL_USER: peatio
      MYSQL_PASSWORD: changeme

  redis:
    image: redis:alpine
    restart: always

  rabbitmq:
    image: rabbitmq:alpine
    restart: always

  selenium:
    image: selenium/standalone-chrome
    restart: always
    environment:
      SCREEN_WIDTH: 800
      SCREEN_HEIGHT: 600

volumes:
  db_data:
