- key:               eth-rinkeby
  name:              Ethereum Rinkeby
  client:            ethereum
  server:            http://10.8.0.1:8545
  height:            2756436
  min_confirmations: 6
  explorer:
    address:         https://rinkeby.etherscan.io/address/#{address}
    transaction:     https://rinkeby.etherscan.io/tx/#{txid}
  status:            active

- key:               grin-floonet
  name:              Grin Floonet
  client:            grin
  server:            http://10.8.0.1:25003
  height:            8500
  min_confirmations: 10
  explorer:
    address:         https://grinexplorer.net
    transaction:     https://grinexplorer.net
  status:            active